"""Regenerate every number quoted in REPORT.md -> results/summary.json + results/RESULTS.md."""
from __future__ import annotations

import json
from dataclasses import replace
from pathlib import Path

import numpy as np
import pandas as pd

from .analysis import bootstrap_loss_probs, cagr, rolling_loss_probs, stats, walk_forward
from .backtest import run_backtest
from .config import CostConfig, StrategyConfig, TaxConfig
from .data import build_dataset, shiller_long_equity
from .economics import EconAssumptions, annual_economics, sensitivity
from .strategies import presets

OUT = Path(__file__).resolve().parent.parent / "results"
TAX_OFF = TaxConfig(enabled=False)
TAX_ON = TaxConfig()


def pct(x: float, d: int = 1) -> str:
    return f"{x * 100:.{d}f}%"


def liq_cagr(res, years: float) -> float:
    return (res.liquidation_value / res.contributions.iloc[-1]) ** (1 / years) - 1


def gross_index_cagr(data: pd.DataFrame, targets: dict) -> float:
    cols = {"stock": "stock_tr", "bond": "bond_tr", "bill": "bill_tr"}
    r = sum(w * data[cols[a]] for a, w in targets.items())
    return cagr(r.iloc[1:])


def main() -> dict:
    OUT.mkdir(exist_ok=True)
    data = build_dataset()
    years = (len(data) - 1) / 12
    S: dict = {"period": f"{data.index[0]}..{data.index[-1]}", "years": years}
    md: list[str] = [f"# Results (auto-generated by `python -m investengine.cli backtest`)\n",
                     f"Data: {S['period']} monthly ({years:.0f} years). $100,000 lump sum, no withdrawals.\n"]

    # 1) asset stats
    md.append("## Asset classes (gross, before any cost)\n\n| asset | CAGR | vol |\n|---|---|---|")
    for c in ["stock_tr", "bond_tr", "bill_tr", "infl"]:
        md.append(f"| {c} | {pct(cagr(data[c]), 2)} | {pct(data[c].std() * np.sqrt(12))} |")
        S.setdefault("assets", {})[c] = {"cagr": cagr(data[c]), "vol": float(data[c].std() * np.sqrt(12))}

    # 2) full-period engine backtests
    md.append("\n## Engine backtests, full period\n")
    md.append("| strategy | account | CAGR (TWR) | after-liquidation CAGR | real CAGR | max DD | longest underwater (mo) | Sharpe | taxes paid | trading costs | fund fees | turnover/yr | drag vs gross index |")
    md.append("|---|---|---|---|---|---|---|---|---|---|---|---|---|")
    S["backtests"] = {}
    results = {}
    for name, strat in presets().items():
        for acct, tax in (("IRA", TAX_OFF), ("taxable", TAX_ON)):
            if strat.tlh and acct == "IRA":
                continue
            res = run_backtest(data, strat, tax=tax)
            results[(name, acct)] = res
            r = res.monthly_returns
            st = stats(r, data["bill_tr"], data["infl"])
            lc = liq_cagr(res, years)
            drag = gross_index_cagr(data, strat.targets) - lc
            S["backtests"][f"{name}|{acct}"] = {**st, "liq_cagr": lc, "drag": drag,
                                                "taxes_paid": res.taxes_paid, "trading_costs": res.trading_costs,
                                                "expense_drag": res.expense_drag, "turnover": res.turnover,
                                                "harvested_losses": res.harvested_losses,
                                                "final_value": float(res.values.iloc[-1]),
                                                "liquidation_value": res.liquidation_value}
            md.append(f"| {name} | {acct} | {pct(st['cagr'], 2)} | {pct(lc, 2)} | {pct(st['real_cagr'], 2)} | "
                      f"{pct(st['max_drawdown'])} | {st['longest_underwater_months']} | {'n/a' if np.isnan(st['sharpe']) else format(st['sharpe'], '.2f')} | "
                      f"${res.taxes_paid:,.0f} | ${res.trading_costs:,.0f} | ${res.expense_drag:,.0f} | "
                      f"{res.turnover:.2f} | {drag * 1e4:.0f} bp |")

    # 3) historical rolling loss probabilities
    md.append("\n## Probability of loss - historical overlapping windows (engine returns, after costs)\n")
    md.append("Overlapping windows are not independent: ~95 independent 1y, 19 independent 5y and 9 independent 10y periods exist.\n")
    md.append("| strategy | account | horizon | P(nominal loss) | P(real loss) | P(trail T-bills) | worst ann. | median ann. |")
    md.append("|---|---|---|---|---|---|---|---|")
    S["rolling"] = {}
    for key in [("bills", "IRA"), ("stocks100", "IRA"), ("s80_b20", "IRA"), ("s60_b40", "IRA"),
                ("s40_b60", "IRA"), ("s60_b40", "taxable"), ("s60_b40_trend10", "IRA")]:
        rp = rolling_loss_probs(results[key].monthly_returns, data["bill_tr"], data["infl"])
        S["rolling"]["|".join(key)] = rp
        for h, v in rp.items():
            md.append(f"| {key[0]} | {key[1]} | {h} | {pct(v['p_nominal_loss'])} | {pct(v['p_real_loss'])} | "
                      f"{pct(v['p_below_bills'])} | {pct(v['worst_annualized'])} | {pct(v['median_annualized'])} |")
    lr = shiller_long_equity()
    rp = rolling_loss_probs(lr["stock_tr"], pd.Series(0.0, index=lr.index), lr["infl"])
    S["rolling"]["shiller_stocks_1871_2023_gross"] = rp
    md.append("\nRobustness, S&P composite 1871-2023 (Shiller, gross, monthly-average prices):\n")
    for h, v in rp.items():
        md.append(f"- {h}: P(nominal loss) {pct(v['p_nominal_loss'])}, P(real loss) {pct(v['p_real_loss'])}, worst ann. {pct(v['worst_annualized'])}")

    # 4) bootstrap
    md.append("\n## Probability of loss - block bootstrap (10,000 paths, mean block 24 months)\n")
    md.append("Drag = measured engine drag (costs+fees, and taxes for taxable). Haircut = equity return reduced by 3%/yr to reflect lower forward expectations.\n")
    md.append("| strategy | account | equity haircut | horizon | P(nominal loss) | P(real loss) | P(trail T-bills) | 5th pct ann. | median ann. |")
    md.append("|---|---|---|---|---|---|---|---|---|")
    S["bootstrap"] = {}
    for name, acct in [("stocks100", "IRA"), ("s80_b20", "IRA"), ("s60_b40", "IRA"), ("s40_b60", "IRA"),
                       ("s60_b40", "taxable")]:
        strat = presets()[name]
        # floor: never assume less drag than fund fees + 2bp (5/25 bands showed a
        # small rebalancing bonus vs a monthly-rebalanced index; we do not bank on it)
        er = 0.0003 * strat.targets.get("stock", 0) + 0.0015 * strat.targets.get("bond", 0)
        drag = max(S["backtests"][f"{name}|{acct}"]["drag"], er + 0.0002)
        for hc in (0.0, 0.03):
            bp = bootstrap_loss_probs(data, strat.targets, drag, stock_haircut=hc)
            S["bootstrap"][f"{name}|{acct}|haircut{hc}"] = bp
            for h, v in bp.items():
                md.append(f"| {name} | {acct} | {pct(hc, 0)} | {h} | {pct(v['p_nominal_loss'])} | "
                          f"{pct(v['p_real_loss'])} | {pct(v['p_below_bills'])} | {pct(v['p05_annualized'])} | "
                          f"{pct(v['median_annualized'])} |")

    # 5) walk-forward of overlays / rebalancing rules
    base = presets()["s60_b40"]
    cands = [base] + [replace(base, name=f"trend{n}", trend_sma=n) for n in (6, 8, 10, 12)] + [
        replace(base, name="band10", band_abs=0.10, band_rel=0.5),
        replace(base, name="annual", band_abs=1.0, band_rel=10.0, calendar_months=12)]
    S["walk_forward"] = {}
    md.append("\n## Walk-forward (expanding window, 10-year out-of-sample blocks 1951-2021)\n")
    md.append("Candidates: 60/40 with 5/25 bands (base), +trend overlay SMA 6/8/10/12, wider 10/50 bands, annual calendar. Selected by in-sample Sharpe (tax-free).\n")
    for acct, tax in (("IRA", TAX_OFF), ("taxable", TAX_ON)):
        wf = walk_forward(data, base, cands, tax=tax)
        b = data["bill_tr"]
        s_sel, s_base = stats(wf["selected"], b, data["infl"]), stats(wf["base"], b, data["infl"])
        S["walk_forward"][acct] = {"blocks": wf["blocks"], "selected": s_sel, "base": s_base}
        md.append(f"**{acct}**: OOS selected-rule CAGR {pct(s_sel['cagr'], 2)}, maxDD {pct(s_sel['max_drawdown'])}, "
                  f"Sharpe {s_sel['sharpe']:.2f} | base 60/40 CAGR {pct(s_base['cagr'], 2)}, maxDD {pct(s_base['max_drawdown'])}, "
                  f"Sharpe {s_base['sharpe']:.2f}\n")
        if acct == "IRA":
            md.append("| test block | chosen | in-sample Sharpe |\n|---|---|---|")
            for blk in wf["blocks"]:
                md.append(f"| {blk['test']} | {blk['chosen']} | {blk['train_sharpe']:.2f} |")
            md.append("")

    # 6) tax-loss harvesting value across start dates (20-year taxable windows)
    md.append("\n## Tax-loss harvesting: after-liquidation CAGR, taxable, 20-year windows\n")
    md.append("| start | contrib/mo | 60/40 | 60/40+TLH | TLH alpha | 100% stock | 100% stock+TLH | TLH alpha |")
    md.append("|---|---|---|---|---|---|---|---|")
    S["tlh"] = []
    for start in ("1929-06", "1937-01", "1966-01", "1973-01", "1987-06", "2000-01"):
        win = data.loc[start:].iloc[:241]
        if len(win) < 241:
            continue
        for contrib in (0.0, 1000.0):
            row = {"start": start, "contrib": contrib}
            for nm in ("s60_b40", "s60_b40_tlh", "stocks100", "stocks100_tlh"):
                res = run_backtest(win, presets()[nm], tax=TAX_ON, monthly_contribution=contrib)
                row[nm] = irr_monthly(res)
            S["tlh"].append(row)
            md.append(f"| {start} | ${contrib:,.0f} | {pct(row['s60_b40'], 2)} | {pct(row['s60_b40_tlh'], 2)} | "
                      f"{(row['s60_b40_tlh'] - row['s60_b40']) * 1e4:+.0f} bp | {pct(row['stocks100'], 2)} | "
                      f"{pct(row['stocks100_tlh'], 2)} | {(row['stocks100_tlh'] - row['stocks100']) * 1e4:+.0f} bp |")
    al = [r["s60_b40_tlh"] - r["s60_b40"] for r in S["tlh"]]
    S["tlh_alpha_6040_mean"] = float(np.mean(al))
    md.append(f"\nMean 60/40 TLH alpha: {np.mean(al) * 1e4:+.0f} bp/yr (min {min(al) * 1e4:+.0f}, max {max(al) * 1e4:+.0f}).\n")

    # 7) cost stress
    md.append("\n## Cost stress (60/40, IRA, full period)\n\n| spread x | slippage bp | commission/order | after-liq CAGR |\n|---|---|---|---|")
    S["cost_stress"] = []
    for mult, slip, comm in ((1, 1, 0), (5, 5, 0), (10, 10, 0), (1, 1, 5.0)):
        res = run_backtest(data, base, tax=TAX_OFF, cost=CostConfig(comm, slip, mult))
        lc = liq_cagr(res, years)
        S["cost_stress"].append({"spread_mult": mult, "slippage_bps": slip, "commission": comm, "liq_cagr": lc})
        md.append(f"| {mult} | {slip} | ${comm} | {pct(lc, 2)} |")

    # 8) forward-looking economics
    tdrag = S["backtests"]["s60_b40|IRA"]["liq_cagr"] - S["backtests"]["s60_b40|taxable"]["liq_cagr"]
    base_a = EconAssumptions(turnover=S["backtests"]["s60_b40|IRA"]["turnover"])
    S["econ"] = {"historical_tax_drag_6040": tdrag, "base": base_a.__dict__, "by_account": []}
    md.append("\n## Forward-looking economics (ASSUMED returns; 60/40)\n")
    md.append(f"Assumptions: stocks {pct(base_a.stock_return)}, bonds {pct(base_a.bond_return)}, bills {pct(base_a.bill_return)}, inflation {pct(base_a.inflation)}, "
              f"blended ER {pct(base_a.expense_ratio, 2)}, turnover {base_a.turnover:.2f}/yr at {base_a.trade_cost_bps}bp, fixed ${base_a.fixed_cost_per_year:.0f}/yr. "
              f"Taxable rows use the historical tax drag {pct(tdrag, 2)}/yr measured by the engine.\n")
    md.append("| account | type | net return | expected $ gain/yr | real $ gain/yr | vs T-bills $/yr | fee saved vs 0.25% robo $/yr |\n|---|---|---|---|---|---|---|")
    for acct in (5_000, 10_000, 50_000, 100_000, 500_000):
        for typ, a in (("IRA", base_a), ("taxable", replace(base_a, tax_drag=tdrag, bill_tax_rate=0.24))):
            e = annual_economics(acct, 0.6, 0.4, a)
            S["econ"]["by_account"].append({"type": typ, **e})
            md.append(f"| ${acct:,} | {typ} | {pct(e['net_return_rate'], 2)} | ${e['expected_net_gain']:,.0f} | "
                      f"${e['expected_real_gain']:,.0f} | ${e['expected_gain_vs_tbills']:,.0f} | ${e['fee_saved_vs_robo']:,.0f} |")
    e0 = annual_economics(100_000, 0.6, 0.4, base_a)
    S["econ"]["breakeven_nominal"] = e0["breakeven_account_nominal"]
    S["econ"]["breakeven_vs_robo"] = e0["breakeven_account_vs_robo"]
    md.append(f"\nBreak-even account size (expected gain covers ${base_a.fixed_cost_per_year:.0f}/yr fixed cost): "
              f"${e0['breakeven_account_nominal']:,.0f}; vs a 0.25% robo fee: ${e0['breakeven_account_vs_robo']:,.0f}.\n")
    sens = sensitivity(base=base_a)
    neg = [r for r in sens if r["expected_net_gain"] <= 0]
    negc = [r for r in sens if r["expected_gain_vs_tbills"] <= 0]
    S["econ"]["sensitivity_n"] = len(sens)
    S["econ"]["sensitivity_negative"] = len(neg)
    S["econ"]["sensitivity_below_tbills"] = len(negc)
    pd.DataFrame(sens).to_csv(OUT / "sensitivity.csv", index=False)
    md.append(f"Sensitivity grid ($100k, {len(sens)} scenarios: stock return 3-8%, ER 0.05-0.30%, trade cost 2-10bp, tax drag 0-0.8%, fixed $0-600): "
              f"expected nominal gain <= 0 in {len(neg)} scenarios; expected to trail after-tax T-bills in {len(negc)} scenarios "
              f"(see results/sensitivity.csv).\n")
    tbl = pd.DataFrame(sens).pivot_table(index="stock_return", columns="fixed_cost", values="expected_gain_vs_tbills", aggfunc="min")
    md.append("Worst-case (over ER/trade-cost/tax combos) expected $/yr vs T-bills, $100k:\n")
    md.append("| stock return | " + " | ".join(f"fixed ${c:.0f}" for c in tbl.columns) + " |")
    md.append("|---|" + "---|" * len(tbl.columns))
    for sr, row in tbl.iterrows():
        md.append(f"| {pct(sr)} | " + " | ".join(f"${v:,.0f}" for v in row) + " |")

    (OUT / "summary.json").write_text(json.dumps(S, indent=2, default=float))
    (OUT / "RESULTS.md").write_text("\n".join(md) + "\n")
    print("\n".join(md))
    return S


def irr_monthly(res) -> float:
    """Annualized money-weighted return using the after-liquidation end value."""
    flows = res.contributions.diff().fillna(res.contributions.iloc[0]).to_numpy()
    n = len(flows)
    end = res.liquidation_value
    lo, hi = -0.99, 1.0
    for _ in range(200):
        mid = (lo + hi) / 2
        m = (1 + mid) ** (1 / 12)
        fv = sum(f * m ** (n - 1 - i) for i, f in enumerate(flows))
        if fv > end:
            hi = mid
        else:
            lo = mid
    return (lo + hi) / 2


if __name__ == "__main__":
    main()
